### PR TITLE
Sprint2

### LINKED ISSUE #19: Destroyable blocks
Add block objects that can be demolished by bombs.

Time estimated: 30 mins
Actual time: 34 mins

* critical bug fix: + 1 hr 20 mins, some of the components removed by accident

### LINKED ISSUE #20: Add simple enemies
Add enemies that walk around the map and do damage to the player when they contact.
*About 1 hr 20 mins were used to implement cross-direction movements and fix bugs

Time estimated: 1 hr
Actual time: 1 hr 46 mins + 20 mins (way to detect damage taken chaged)

### LINKED ISSUE #21: Expand Test Level a little bit
Make the test level bigger and collaborate with objects.
(This plan has been scaled down in response to a number of sudden developments (such as unexpected long-time bug fixes, which was the removal of the component).

Time estimated: 30 hr
Actual time: 36 mins

### LINKED ISSUE #22: Extra work - camera view
Implement camera views and movements that can fit the game better.

Actual time: + 1 hr 30 mins

### LINKED ISSUE #23: Add damage to bomb
Make bomb objects actually do damage to other interactable objects.

Time estimated: 30 mins
Actual time: 28 mins
*extra work (Different damaging condition )

### LINKED ISSUE #24: Add range to bomb
Broaden the scope of the bomb's explosion range

Time estimated: 1 hr
Actual time: 36 mins

### LINKED ISSUE #25: Pick up items
Let pick-up items appear randomly when you demolish the soft blocks. During the test phase, the item must appear with a 50:50 probability in block destruction, and its effect is limited to speeding up the player.

Time estimated: 2 hrs
Actual time: 2 hrs even

### LINKED ISSUE #26: Transferred from Sprint 1 (was not planned to work on)
Snapping the bomb in tile-grid position and Ignore collision between the player and the bomb after it planted.

Time estimated:
Actual time: 1 hr 20 mins + 14 mins

### PR DESCRIPTION
**Pull request by qnf613**
In this sprint, almost all interactions of the bomb have been implemented. Also, the camera view has been changed. Lastly, the test stage added for the playtest.

### CODE REVIEW

File: Assets/Scripts/Enemy.cs [hunk 1]
```diff
@@ -0,0 +1,200 @@
...
+        //death condition
+        if (currentHP <= 0)
+        {
+            Destroy(gameObject);
+        }
+
+        //movement direction
+        switch (nextMove)
+        {
+            case 0:
```
Comment (andyocampo) [inline Assets/Scripts/Enemy.cs:45]: This is a very long switch case that could maybe be reduced by changing each bool that checks whether the enemy is moving into a Vector 2 that simply states the movement vector. For example: NotMoving = new Vector 2(0,0) and when case 0 is selected you invoke NotMoving, or MovingRight = new Vector2(1,0) and when case 4 is chosen, invoke MovingRight. It's a bit hard to understand with all the booleans. Also instead of having nextMove as an int, maybe have it as an Enum so that you can check which state is happening (Up, Down, Left, Right) this will also save some lines as it'll remove the Move() method

**Review by andyocampo — APPROVED** [review]
Looks pretty good, everything is implemented as in the description, my only issue is with the enemy script and the really long switch case, please check the comment I left on that code.

Also on a side note, I kept getting stuck on the blocks it was a bit hard to navigate through them.
